### ISSUE TITLE
TwitterBootstrap3 package should Install-Package Microsoft.AspNet.Web.Optimization

### ISSUE THREAD

**Issue by BluePowerVan** [MRCollective/ChameleonForms#115]
On an empty project that I added Chameleon and the TwitterBootstrap3 to, I could not build due to a missing System.Web.Optimization reference. Had to manually Install-Package Microsoft.AspNet.Web.Optimization to get it to run.

Hope this helps.

**Comment by robdmoore** [comment]
Hi @BluePowerVan,

Thanks for this. You are right - it does add some code that relies on that library. Thanks for picking that up.

In reality the code that is added isn't essential - you could delete it, but I will change the nuspec so it's an explicit dependency so people aren't confused by it.

Thanks again!
