### ISSUE TITLE
ReadOnlyConfiguration class is redundant

### ISSUE THREAD

**Issue by zabulus** [MRCollective/ChameleonForms#119]
I think that ReadOnlyConfiguration class is redundant because it is just forwards all calls to IFieldConfiguration. I think we can delete it without problems, and just make IReadonlyFieldConfiguration a part of IFieldConfiguration. BTW as I see IReadonlyFieldConfiguration is used just for internal purposes, maybe it should be hidden as private? What do you think?

**Comment by robdmoore** [comment]
If you can do this without breaking the public API and without removing IReadonlyFieldConfiguration (it's important) then feel free to submit a PR - would gladly merge that. It's a bit of a pain we have to keep the other class up to date!

**Comment by zabulus** [comment]
Closing this
