### ISSUE TITLE
Expanded form of `@s.FieldFor(m => m.Name)` not equivalent

### ISSUE THREAD

**Issue by jtheisen** [MRCollective/ChameleonForms#126]
I now actually do have the problem that the expanded form

```
        <div class="form-group">
            @f.LabelFor(m => m.Name)
            @f.FieldElementFor(m => m.Name)
            @f.ValidationMessageFor(m => m.Name)
        </div>
```

is not quite the same as `@s.FieldFor(m => m.Name)`.

The problem is that, using the bootstrap template, some additional classes are missing.

`TwitterBootstrapFormTemplate.PrepareFieldConfiguration()` adds those classes to the field configuration:

```
fieldConfiguration.AddValidationClass("help-block");
...
fieldConfiguration.AddClass("form-control").AddLabelClass("control-label");
```

But it only does so if the parent isn't the form:

```
if (fieldParent == FieldParent.Form)
                return;
```

[link to above here](https://github.com/MRCollective/ChameleonForms/blob/master/ChameleonForms/Templates/TwitterBootstrap3/TwitterBootstrapFormTemplate.cs#L34-L35)

It's true that the individual part methods are on the form while the whole package comes as a method on the section. I'm not suggesting a patch since I don't know the rationale for this distinction and why the parent type should make a difference.

For most users this is a non-issue, since they do it all in Javascript with the right bootstrap template fixes done there.

I would think it would be neater if ChameleonForms does this right without js, too.

**Comment by robdmoore** [comment]
So if the parent is the form then that means you are using the `@f.FieldElementFor()` etc. methods and are opting in to take more control over the html. Thus in that instance ChameleonForms can't make assumptions about the surrounding HTML and can't add things like `form-control` and `control-label` etc. You can use the `AddClass` method to add in any classes you need inline.

None of what you describe above requires JavaScript - ChameleonForms works fine without JavaScript.

There is some JavaScript we have written to fix up some problems with the ASP.NET MVC form HTML and Bootstrap styling, but this isn't specific to ChameleonForms - the same problems exist out-of-the-box with ASP.NET MVC: https://github.com/MRCollective/ChameleonForms/blob/master/ChameleonForms.Example/Scripts/jquery.validate.unobtrusive.twitterbootstrap.js

Does that help?

**Comment by robdmoore** [comment]
Closing for now, but feel free to re-open if there is anything more that you need to know.
