### ISSUE TITLE
How to update without loosing my code

### ISSUE THREAD

**Issue by sergy79** [MRCollective/ChameleonForms#138]
Hi, this is an awesome plugin

I have a concern on updating the nuget packages, after I make changes to my data or code. 
How can I easily update this plugin - without loosing my changes, partial classes or is there another way?

thanks
:+1:

**Comment by robdmoore** [comment]
Hi,

Not sure I understand? Updating the NuGet package shouldn't touch any of your code?

**Comment by robdmoore** [comment]
Feel free to sound out if you can clarify your question, but in the meantime I'm closing this as per my last comment.
