### ISSUE TITLE
Is Master Detail suitable?

### ISSUE THREAD

**Issue by net4u** [MRCollective/ChameleonForms#140]
I just found ChameleonForms and I want to clarify a few things:
It is suitable for scenarios master / detail, for example, orders and articles of order? (Add an order and five articles relating to that order using one single Save)
It can be changed using jQuery? For example we have an input for products and we want to support autocomplete for existing values from DB or to open a modal dialog to add a product that not exist yet.

Thank you in advance

**Comment by robdmoore** [comment]
ChameleonForms allows you to do everything that you can do in ASP.NET MVC (it just removes a bunch of boilerplate code and makes your forms more succinct, readable and maintainable).

It mostly involves outputting HTML and assisting MVC to bind your model so beyond that (e.g. using jQuery or Angular etc. to modify the form on the client side, bind complex models that involve children such as order articles, etc.) you have full flexibility to do as you would with normal MVC.

HTH
