### ISSUE TITLE
Using as PartialView and (Bootstrap) Modal

### ISSUE THREAD

**Issue by net4u** [MRCollective/ChameleonForms#147]
Hi,

Is possible to use the same form as PartialView and (sometimes) also as popup Modal ?
I have a scenario where I think to use the same form in a regular Add Customer view, but also to popup the PartialView when I am for example in List Customers view (or even in other views that may be related in this case to Customers, e.g. Add Order view and I find that I don't have a certain Customer in DB, and just want to add it being in Order View)

**Comment by robdmoore** [comment]
You can probably pull it off using the partial functionality: https://chameleonforms.readthedocs.io/en/latest/partials/
