### ISSUE TITLE
Add / Remove Attributes from elementHtml

### ISSUE THREAD

**Issue by mahyarmot** [MRCollective/ChameleonForms#151]
Hi there,
We are going to develop our new template based on our purchased bootstrap theme, but we are facing some challenges which i did not find any solution for them.
As a understood the mechanism, when we define a code like this : 
```
@using (var f = Html.BeginChameleonForm())
    {
        using (var s = f.BeginSection(""))
        {
            @s.FieldFor(m => m.Title).Label(L("CompanyActivityType.Title"))
            @s.FieldFor(m => m.AlternativeTitle).Label(L("CompanyActivityType.AlternativeTitle"))
            @s.FieldFor(m => m.DisplayOrder).Label(L("CompanyActivityType.DisplayOrder")).InlineLabel(L("DisplayOrderHelp"))
            @s.FieldFor(m => m.Description).Label(L("CompanyActivityType.Description"))
        }
    }

```
the razor engine first calls our "PrepareFieldConfiguration" and then "Field" method in our overridden template class and then executes the razor file. The issue is, we want to manipute the attributes of IHtmlString! 
for example the generated html base on the data annotations is : 

`<input class="form-control" data-val="true" data-val-maxlength="The field Title must be a string or array type with a maximum length of '50'." data-val-maxlength-max="50" id="Title" name="Title" value="" type="text">`

but our desired output is : 

`<input class="form-control edited" type="text" id="Title" name="Title" required maxlength="50">`

So we desire removing **data-val** , **data-val-maxlength**, **data-val-maxlength-max** attributes and adding **required** ,  **maxlength** instead.

 Due to the rendering of "elementHtml" in razor file, the only place to add or remove attributes is the "Field" method in our *Template.cs file. I just wondered how can I manipulate the elementHtml so i have the desired html tag.

the following customized files are reachable at  [http://www.devi.ir/metronix.zip](url)

**Comment by robdmoore** [comment]
To remove the `data-val-*` attributes you can simply turn off unobtrusive validation as per http://www.dotnettricks.com/learn/mvc/how-to-enable-and-disable-client-side-validation-in-mvc (i.e. via web.config globally or via HtmlHelper in that view).

If you want to add `required` or other attributes in a cross-cutting way the easiest way would be to override `PrepareFieldConfiguration` in your custom template class (e.g. see what I did here in our Bootstrap one: https://github.com/MRCollective/ChameleonForms/blob/master/ChameleonForms/Templates/TwitterBootstrap3/TwitterBootstrapFormTemplate.cs#L32).

Then you could do something like e.g.:

```csharp
if (fieldGenerator.Metadata.IsRequired)
    fieldConfiguration.Attr("required", "required");
```

**Comment by mahyarmot** [comment]
Dear Rob,
Thanks. The issue is resolved.
