### ISSUE TITLE
Project build error

### ISSUE THREAD

**Issue by leslieharland** [MRCollective/ChameleonForms#159]
The specified task executable location "/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/4.5/aspnet_compiler.exe" is invalid. (MSB6004) (ChameleonForms.Example)

OS: Mac OS X
Visual Studio 2017 

Please help.

Secondly, why do I get error Html.BeginChameleonForm extension. not found?

**Comment by leslieharland** [comment]
I created a new .net mvc app and just realised Chameleon Forms not compatible in a way

**Comment by robdmoore** [comment]
Hi,

Chameleon Forms only works with ASP.NET MVC 5 on full framework at this point in time. It won’t work in dotnet core and this won’t work on a Mac.

--
