### ISSUE TITLE
Documentation around contributing

### ISSUE THREAD

**Issue by becdetat** [MRCollective/ChameleonForms#54]
You guys should write some cheatsheet stuff around setting up the dev environment, navigating the billions of tests, the library's high level structure.

**Comment by robdmoore** [comment]
This is a good example: https://github.com/GitTools/GitVersion/blob/master/CONTRIBUTING.md

**Comment by ItsPugle** [comment]
I'm happy to work on this task, then create a PR - I'll just be rewriting and reworking [the example](https://github.com/GitTools/GitVersion/blob/master/CONTRIBUTING.md) that @robdmoore mentioned, though.

Part of the up-for-grabs system. First time offering to contribute with documentation, so this might be interesting.

**Comment by robdmoore** [comment]
Awesome!

That sounds great :)

Let me know if you have any questions / need any help!
